safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "ChenDaqian"
description: '.NET Egineer'
baseurl: "/"
url: "https://chendaqian.github.io/" # replace by your site's url
cnblog_username: Chendaqian
github_username:  ChenDaqian # (your name)
accent: "#f7f7e6" # accent color for blog column
consoleWrite: true
particlesOutput: true
author: "ChenDaqian"
address: "Beijing, China"
email: "hi.world@outlook.com"

bd_analytics: "6b36e4bf2c83e6e8222e22e0e1151cd3"

# language settings
isolang: zh

# exclude files
exclude:
  - LICENSE
  - README.md
