safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "ChenDaqian"
description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam"
baseurl: "/"
url: "https://lukas-h.github.io" # replace by your site's url
twitter_username: ChenDaqian
github_username:  ChenDaqian # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "ChenDaqian"
address: "Beijing, <br>cn"
email: "hi.world@outlook.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en

# exclude files
exclude:
  - LICENSE
  - README.md
