name: Deploy Jekyll with GitHub Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler: '2.4'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor/bundle
            .jekyll-cache
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site_output  # 修改输出目录避免冲突

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site_output  # 必须与构建输出目录一致
          name: pages-artifact  # 显式命名构件

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact-name: pages-artifact  # 必须与上传名称一致
